name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating_system }}
    strategy:
      matrix:
        operating_system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Generate requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests -p "test_*.py"
